[package]
name = "tfhe-example"
version = "0.1.0"
edition = "2024"

[dependencies]
tfhe = { version = "*", features = ["boolean", "shortint", "integer", "extended-types"] }
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
