[package]
name = "tfhe-floyd"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "~1.0.1", features = ["boolean", "shortint", "integer"] }
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
